on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-eslint-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E ESLint'
jobs:
  chore:
    name: 'Validating ESLint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add eslint

        echo 'export default {"rules": {"semi": ["error", "always"]}}' > eslint.config.mjs

        echo '42;' | tee ok.js
        yarn eslint ok.js

        echo '42' | tee ko.js
        ! yarn eslint ko.js

    - name: 'Running the TypeScript integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add eslint typescript typescript-eslint

        echo "import tseslint from 'typescript-eslint';\n
export default tseslint.config({
  files: ['**/*.ts'],
  plugins: { '@typescript-eslint': tseslint.plugin },
  languageOptions: { parser: tseslint.parser },
  rules: { '@typescript-eslint/explicit-function-return-type': 'error' }
});" > eslint.config.mjs

        echo 'const f = (): number => 42;' | tee ok.ts
        yarn eslint ok.ts

        echo 'const f = () => 42;' | tee ko.ts
        ! yarn eslint ko.ts
      if: |
        success() || failure()
